import Head from 'next/head'
import Image from 'next/image'
import { Raleway} from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Sidebar from '@/components/Sidebar'
import { useEffect } from 'react';
import HomeCarousel from '@/components/HomeCarousel'
import Footer from '@/components/footer'
import SearchForm from '@/components/SearchForm'

const inter = Raleway({ subsets: ['latin'] })

export default function Home() {
    return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <header className="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
            <a className="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Next Hotel</a>
            <button className="navbar-toggler position-absolute d-md-none collapsed" type="button"
                    data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
            </button>
        </header>

        <div className="container-fluid">
            <div className="row">
                <Sidebar />
                <main className="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                    <HomeCarousel />
                    <SearchForm />
                    <Footer/>
                </main>
            </div>
        </div>
    </>
  )
}
