import Head from 'next/head'
import { Raleway} from '@next/font/google'
import styles from '@/styles/Home.module.css'
import BootStrapCarouselExample from '@/pages/home_carousel_example'

const inter = Raleway({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>next Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
            <BootStrapCarouselExample />
      </main>
    </>
  )
}
